### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by KFlash** [escaya/escaya-codegen#1]
Too much ;)

- [ ] Work with and without 'cst' option in EScaya enabled

- [ ] Add context masks to track state and solve edge cases

- [ ] Add options for prettier output

- [ ] Add option to remove whitespace

- [ ] Add option for semicol

- [ ] Handle comments

**Under consideration**

- [ ] Tons of options to handle different output aka prettier

- [ ] Add option to minify the source

**Comment by KFlash** [comment]
Default styling will be something like this. It will all be optional.

![defindent](https://user-images.githubusercontent.com/31855118/92610141-f3cfb900-f2e9-11ea-93ad-63277c84f78e.png)

**Comment by KFlash** [comment]
Still need to verify correct output and that all edge cases have been solved.

**Comment by KFlash** [comment]
@aladdin-add can you try to find bugs in this generator? Switch statements I'm aware of

**Comment by axefrog** [comment]
Now THIS is something that excites me!

Serializing code from an AST to actual JavaScript is an absolutely critical use case for me. If I could email you a bouquet of flowers, I would :D

At the very least, I'll be happy to show you what I'm using it for once I get past this giant milestone I've been working on seemingly forever now.

**Comment by KFlash** [comment]
Yeah this is the result of creating your own AST. There are no existing tools, so I was forced to create one. 

Actually I was in the middle of finishing the Escaya parser, but I didn't have a fuzzer.... So I was forced to create one, but then I was missing a code gen to test the output against. And then the ball just kept rolling...

I also added a minifier option to test how my AST  would work as an minified version. Not done with that yet. I still have to adopt all the Terser options and to some code transform.

Anyway. For now this is just a basic blazing fast code gen as of now with a few options so I can finalize the fuzzer, and contributors are welcome.

Yeah. Would be interesting to see what you are developing. It may give me a few ideas to improve this tools as well.

**Comment by axefrog** [comment]
> minified version
> blazing fast

Sounds great to me 👍

**Comment by KFlash** [comment]
My biggest problem is that I have only 10 hours left of my available time to finish the basic codegen and some other things. After that my closest family will return after 8 months isolated due to covid and I go offline for days. They had a travel ban that has now  been lifted 👍
